name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Prepare"
        uses: ./.github/actions/prepare

      - name: "Install SFDX CLI"
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: "Lint"
        run: pnpm lint

      - name: "Prettier Check"
        run: pnpm prettier:verify

      - name: "Run Tests"
        run: pnpm test
